/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.89
 * Generated at: 2023-06-11 13:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class request_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("	a:link { color:black; text-decoration:none; }\r\n");
      out.write("	a:visited { color:black; text-decoration:none; }\r\n");
      out.write("	a:hover { color:black; text-decoration:underline; }\r\n");
      out.write("	table, th, td {\r\n");
      out.write("	border:2px solid black;\r\n");
      out.write("	border-collapse : collapse;\r\n");
      out.write("	}\r\n");
      out.write("	tr { height:30px;}\r\n");
      out.write("	th { background-color:#5B9BD5; color:white;}\r\n");
      out.write("	td { text-align:center;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function rl_reply_use_show (rl_reply_use) {\r\n");
      out.write("		if (rl_reply_use == \"y\") {\r\n");
      out.write("			document.getElementById(\"rl_reply_write\").style.display=\"\";\r\n");
      out.write("		} else {\r\n");
      out.write("			document.getElementById(\"rl_reply_write\").style.display=\"none\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div width=\"1100\">\r\n");
      out.write("<input type=\"button\" value=\"전체글\">  게시판 요청<br /><br />\r\n");
      out.write("<form action=\"request_proc.jsp\">\r\n");
      out.write("	<table width=\"1100\" >\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\">아이디</td>\r\n");
      out.write("			<td width=\"30%\">홍길동</td>\r\n");
      out.write("			<td width=\"20%\">작성일</td>\r\n");
      out.write("			<td width=\"30%\">2023-06-09</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>제목</td>\r\n");
      out.write("			<td colspan=\"3\"><textarea style=\"width:870px; height:20px\" name=\"rl_title\">홍길동 키우기 게임게시판 요청글 제목 입니다</textarea></td>\r\n");
      out.write("		</tr >\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>분류</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select name=\"rl_ctgr\" style=\"width:250px; height:25px; font-size:15px;\">\r\n");
      out.write("					<option value=\"a\" >게임</option>\r\n");
      out.write("					<option value=\"b\" >연예</option>\r\n");
      out.write("					<option value=\"c\" >스포츠</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>게시글 작성 권한</td>\r\n");
      out.write("			<td><label>회원<input type=\"radio\" name=\"rl_write\" value=\"y\" /></label><label>비회원<input type=\"radio\" name=\"rl_write\" value=\"n\" /></label></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>댓글 사용 여부</td>\r\n");
      out.write("			<td colspan=\"3\"><label>사용<input type=\"radio\" name=\"rl_reply_use\" value=\"y\" onclick=\"rl_reply_use_show(this.value)\" /></label><label>미사용<input type=\"radio\" name=\"rl_reply_use\" value=\"n\" onclick=\"rl_reply_use_show(this.value)\" /></label>\r\n");
      out.write("            </td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr id=\"rl_reply_write\" style=\"display:none;\">\r\n");
      out.write("			<td>댓글 작성 권한</td>\r\n");
      out.write("			<td colspan=\"3\"><label>회원<input type=\"radio\" name=\"rl_reply_write\" value=\"y\" /></label><label>비회원<input type=\"radio\" name=\"rl_reply_write\" value=\"n\" /></label>\r\n");
      out.write("            </td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>게시판 이름</td>\r\n");
      out.write("			<td colspan=\"3\"><textarea style=\"width:870px; height:20px\" name=\"rl_name\">홍길동 키우기 게임</textarea></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>요청 내용</td>\r\n");
      out.write("			<td colspan=\"3\"><textarea style=\"width:99%; height:100px\">홍길동 키우기 게임게시판 요청글 내용 입니다</textarea></td>\r\n");
      out.write("		</tr>		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"4\">※ 게시판 이름 및 분류와 맞지 않거나, 요청 내용이 부적절할 경우 반려될 수 있습니다..</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>			\r\n");
      out.write("			<td colspan=\"4\">※ 개설 승인, 반려는 매우 많은 시간이 필요합니다.</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table><br />\r\n");
      out.write("	<input style=\"position: fixed;  top: 420px;  left: 1000px;\" type=\"submit\" value=\"등록\"><input style=\"position: fixed;  top: 420px;  left: 1050px;\" type=\"button\" value=\"취소\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
